version: '3.8'

services:
  backend:
    build:
      context: . 
      dockerfile: backend/Dockerfile 
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    restart: unless-stopped
    container_name: wallet_tracer_backend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile 
    ports:
      - "8502:8501"
    environment:
      - BACKEND_URL=http://backend:8000/api/v1
    depends_on:
      - backend
    restart: unless-stopped
    container_name: wallet_tracer_frontend

  nginx:
    image: nginx:latest
    ports:
      - "80:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    container_name: wallet_tracer_nginx
