version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: leandix_backend
    expose:
      - 8000

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.backend 
    container_name: leandix_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - backend
